import type { Client, ClientStage } from "../model/types";

/** Клиент фикстуры без стадии воронки — стадия добавляется ниже. */
type ClientSeed = Omit<Client, "stage">;

const seed: ClientSeed[] = [
  {
    id: "1",
    name: "Посудная лавка «Изумруд»",
    initials: "ПИ",
    color: "#6366f1",
    niche: "retail",
    plan: "full",
    fixedPrice: false,
    status: "active",
    mrr: 70000,
    healthScore: 92,
    health: { activity: 95, integrations: 88, payments: 100, support: 85 },
    connectedAt: "2024-03-15",
    hoursThisMonth: 3,
    manager: "Андрей К.",
    owner: { name: "Сергей Воронов", email: "voronov@izumrud.ru", phone: "+7 916 234-56-78" },
    size: "12 сотрудников",
    nextAction: "Ежеквартальный отзыв",
    daysInStatus: 127,
    notes: "Отличный клиент, всё платит вовремя. Думает о переходе на корпоративный тариф.",
    integrations: [
      { id: "1c", name: "1С", status: "ok", lastSync: "2026-09-06T08:14:00" },
      { id: "moysklad", name: "МойСклад", status: "ok", lastSync: "2026-09-06T09:01:00" },
      { id: "ozon", name: "Ozon", status: "ok", lastSync: "2026-09-06T07:30:00" },
      { id: "wb", name: "Wildberries", status: "disconnected", lastSync: null },
      { id: "cdek", name: "СДЭК", status: "ok", lastSync: "2026-09-05T22:00:00" },
      { id: "whatsapp", name: "WhatsApp", status: "ok", lastSync: "2026-09-06T09:10:00" },
      { id: "telegram", name: "Telegram", status: "ok", lastSync: "2026-09-06T09:10:00" },
      { id: "site", name: "Сайт", status: "ok", lastSync: "2026-09-06T08:00:00" },
    ],
    onboardingSteps: [
      { id: "s1", title: "Анализ бизнеса", status: "done", assignee: "Андрей К.", hoursSpent: 4, dueDate: "2024-03-20" },
      { id: "s2", title: "Интеграции", status: "done", assignee: "Дмитрий Л.", hoursSpent: 12, dueDate: "2024-04-01" },
      { id: "s3", title: "Обучение команды", status: "done", assignee: "Мария С.", hoursSpent: 6, dueDate: "2024-04-10" },
      { id: "s4", title: "Запуск", status: "done", assignee: "Андрей К.", hoursSpent: 2, dueDate: "2024-04-15" },
    ],
    payments: [
      { id: "p1", date: "2026-09-01", amount: 70000, status: "paid", description: "Тариф «Полный» — сентябрь 2026" },
      { id: "p2", date: "2026-08-01", amount: 70000, status: "paid", description: "Тариф «Полный» — август 2026" },
      { id: "p3", date: "2026-07-01", amount: 70000, status: "paid", description: "Тариф «Полный» — июль 2026" },
    ],
  },
  {
    id: "2",
    name: "Интернет-магазин «Модный квартал»",
    initials: "МК",
    color: "#8b5cf6",
    niche: "retail",
    plan: "full",
    fixedPrice: false,
    status: "active",
    mrr: 70000,
    healthScore: 78,
    health: { activity: 82, integrations: 70, payments: 100, support: 60 },
    connectedAt: "2024-05-20",
    hoursThisMonth: 7,
    manager: "Мария С.",
    owner: { name: "Ольга Стрельникова", email: "olga@modnyj.ru", phone: "+7 926 345-67-89" },
    size: "8 сотрудников",
    nextAction: "Решить проблему с Wildberries",
    daysInStatus: 84,
    notes: "Периодические вопросы по интеграции с WB. Нужен созвон на этой неделе.",
    integrations: [
      { id: "1c", name: "1С", status: "ok", lastSync: "2026-09-06T08:00:00" },
      { id: "moysklad", name: "МойСклад", status: "ok", lastSync: "2026-09-06T09:00:00" },
      { id: "ozon", name: "Ozon", status: "ok", lastSync: "2026-09-06T08:30:00" },
      { id: "wb", name: "Wildberries", status: "error", lastSync: "2026-09-05T14:00:00", errorMessage: "Ошибка авторизации API v2. Токен истёк." },
      { id: "cdek", name: "СДЭК", status: "ok", lastSync: "2026-09-06T07:00:00" },
      { id: "whatsapp", name: "WhatsApp", status: "ok", lastSync: "2026-09-06T09:05:00" },
      { id: "telegram", name: "Telegram", status: "ok", lastSync: "2026-09-06T09:05:00" },
      { id: "site", name: "Сайт", status: "ok", lastSync: "2026-09-06T08:00:00" },
    ],
    onboardingSteps: [
      { id: "s1", title: "Анализ бизнеса", status: "done", assignee: "Мария С.", hoursSpent: 3, dueDate: "2024-05-25" },
      { id: "s2", title: "Интеграции", status: "done", assignee: "Дмитрий Л.", hoursSpent: 18, dueDate: "2024-06-10" },
      { id: "s3", title: "Обучение команды", status: "done", assignee: "Мария С.", hoursSpent: 5, dueDate: "2024-06-20" },
      { id: "s4", title: "Запуск", status: "done", assignee: "Мария С.", hoursSpent: 3, dueDate: "2024-06-25" },
    ],
    payments: [
      { id: "p1", date: "2026-09-01", amount: 70000, status: "paid", description: "Тариф «Полный» — сентябрь 2026" },
      { id: "p2", date: "2026-08-01", amount: 70000, status: "paid", description: "Тариф «Полный» — август 2026" },
    ],
  },
  {
    id: "3",
    name: "ТД «Хозяин»",
    initials: "ХЗ",
    color: "#06b6d4",
    niche: "retail",
    plan: "early_access",
    fixedPrice: true,
    status: "onboarding",
    mrr: 5000,
    healthScore: 65,
    health: { activity: 70, integrations: 50, payments: 100, support: 40 },
    connectedAt: "2026-08-01",
    hoursThisMonth: 22,
    manager: "Дмитрий Л.",
    owner: { name: "Николай Хозин", email: "n.khozin@td-khozyain.ru", phone: "+7 903 456-78-90" },
    size: "25 сотрудников",
    nextAction: "Завершить настройку 1С",
    daysInStatus: 36,
    notes: "Крупный торговый дом. Сложная структура 1С. Застряли на этапе интеграций.",
    integrations: [
      { id: "1c", name: "1С", status: "error", lastSync: null, errorMessage: "Не удаётся подключиться к серверу 1С. Проверьте настройки VPN." },
      { id: "moysklad", name: "МойСклад", status: "disconnected", lastSync: null },
      { id: "ozon", name: "Ozon", status: "disconnected", lastSync: null },
      { id: "wb", name: "Wildberries", status: "disconnected", lastSync: null },
      { id: "cdek", name: "СДЭК", status: "ok", lastSync: "2026-09-05T18:00:00" },
      { id: "whatsapp", name: "WhatsApp", status: "ok", lastSync: "2026-09-06T09:00:00" },
      { id: "telegram", name: "Telegram", status: "disconnected", lastSync: null },
      { id: "site", name: "Сайт", status: "disconnected", lastSync: null },
    ],
    onboardingSteps: [
      { id: "s1", title: "Анализ бизнеса", status: "done", assignee: "Дмитрий Л.", hoursSpent: 6, dueDate: "2026-08-07" },
      { id: "s2", title: "Интеграции", status: "in_progress", assignee: "Дмитрий Л.", hoursSpent: 14, dueDate: "2026-09-15" },
      { id: "s3", title: "Обучение команды", status: "pending", assignee: "Мария С.", hoursSpent: 0, dueDate: "2026-09-25" },
      { id: "s4", title: "Запуск", status: "pending", assignee: "Дмитрий Л.", hoursSpent: 0, dueDate: "2026-10-01" },
    ],
    payments: [
      { id: "p1", date: "2026-08-01", amount: 5000, status: "paid", description: "Ранний доступ — август 2026" },
      { id: "p2", date: "2026-09-01", amount: 5000, status: "pending", description: "Ранний доступ — сентябрь 2026" },
    ],
  },
  {
    id: "4",
    name: "Детский мир «Карапуз»",
    initials: "КД",
    color: "#f59e0b",
    niche: "retail",
    plan: "full",
    fixedPrice: false,
    status: "active",
    mrr: 70000,
    healthScore: 52,
    health: { activity: 45, integrations: 60, payments: 60, support: 43 },
    connectedAt: "2024-09-10",
    hoursThisMonth: 14,
    manager: "Андрей К.",
    owner: { name: "Татьяна Морозова", email: "t.morozova@karapuz.shop", phone: "+7 915 567-89-01" },
    size: "18 сотрудников",
    nextAction: "Созвон по просроченному платежу",
    daysInStatus: 180,
    notes: "Падает активность. Просрочен платёж за август. Нужен срочный созвон.",
    integrations: [
      { id: "1c", name: "1С", status: "ok", lastSync: "2026-09-04T14:00:00" },
      { id: "moysklad", name: "МойСклад", status: "ok", lastSync: "2026-09-04T15:00:00" },
      { id: "ozon", name: "Ozon", status: "error", lastSync: "2026-09-01T10:00:00", errorMessage: "Превышен лимит запросов. Требуется обновление тарифа Ozon API." },
      { id: "wb", name: "Wildberries", status: "ok", lastSync: "2026-09-05T20:00:00" },
      { id: "cdek", name: "СДЭК", status: "ok", lastSync: "2026-09-05T22:00:00" },
      { id: "whatsapp", name: "WhatsApp", status: "ok", lastSync: "2026-09-06T08:00:00" },
      { id: "telegram", name: "Telegram", status: "ok", lastSync: "2026-09-06T08:00:00" },
      { id: "site", name: "Сайт", status: "ok", lastSync: "2026-09-06T07:00:00" },
    ],
    onboardingSteps: [
      { id: "s1", title: "Анализ бизнеса", status: "done", assignee: "Андрей К.", hoursSpent: 4, dueDate: "2024-09-15" },
      { id: "s2", title: "Интеграции", status: "done", assignee: "Дмитрий Л.", hoursSpent: 10, dueDate: "2024-09-28" },
      { id: "s3", title: "Обучение команды", status: "done", assignee: "Мария С.", hoursSpent: 8, dueDate: "2024-10-05" },
      { id: "s4", title: "Запуск", status: "done", assignee: "Андрей К.", hoursSpent: 2, dueDate: "2024-10-10" },
    ],
    payments: [
      { id: "p1", date: "2026-09-01", amount: 70000, status: "pending", description: "Тариф «Полный» — сентябрь 2026" },
      { id: "p2", date: "2026-08-01", amount: 70000, status: "overdue", description: "Тариф «Полный» — август 2026" },
      { id: "p3", date: "2026-07-01", amount: 70000, status: "paid", description: "Тариф «Полный» — июль 2026" },
    ],
  },
  {
    id: "5",
    name: "Магазин одежды «Тренд»",
    initials: "ТР",
    color: "#ec4899",
    niche: "retail",
    plan: "early_access",
    fixedPrice: true,
    status: "onboarding",
    mrr: 5000,
    healthScore: 72,
    health: { activity: 75, integrations: 65, payments: 100, support: 50 },
    connectedAt: "2026-08-15",
    hoursThisMonth: 18,
    manager: "Мария С.",
    owner: { name: "Алина Козлова", email: "a.kozlova@trend-store.ru", phone: "+7 977 678-90-12" },
    size: "6 сотрудников",
    nextAction: "Обучение команды по CRM",
    daysInStatus: 22,
    notes: "Молодая команда, быстро обучается. Интеграции почти готовы.",
    integrations: [
      { id: "1c", name: "1С", status: "ok", lastSync: "2026-09-06T08:00:00" },
      { id: "moysklad", name: "МойСклад", status: "ok", lastSync: "2026-09-06T08:30:00" },
      { id: "ozon", name: "Ozon", status: "disconnected", lastSync: null },
      { id: "wb", name: "Wildberries", status: "ok", lastSync: "2026-09-05T22:00:00" },
      { id: "cdek", name: "СДЭК", status: "ok", lastSync: "2026-09-05T23:00:00" },
      { id: "whatsapp", name: "WhatsApp", status: "ok", lastSync: "2026-09-06T09:00:00" },
      { id: "telegram", name: "Telegram", status: "ok", lastSync: "2026-09-06T09:00:00" },
      { id: "site", name: "Сайт", status: "error" as const, lastSync: null, errorMessage: "Сайт в процессе настройки." },
    ],
    onboardingSteps: [
      { id: "s1", title: "Анализ бизнеса", status: "done", assignee: "Мария С.", hoursSpent: 3, dueDate: "2026-08-20" },
      { id: "s2", title: "Интеграции", status: "done", assignee: "Дмитрий Л.", hoursSpent: 8, dueDate: "2026-08-30" },
      { id: "s3", title: "Обучение команды", status: "in_progress", assignee: "Мария С.", hoursSpent: 4, dueDate: "2026-09-10" },
      { id: "s4", title: "Запуск", status: "pending", assignee: "Мария С.", hoursSpent: 0, dueDate: "2026-09-20" },
    ],
    payments: [
      { id: "p1", date: "2026-08-15", amount: 5000, status: "paid", description: "Ранний доступ — август 2026" },
      { id: "p2", date: "2026-09-01", amount: 5000, status: "paid", description: "Ранний доступ — сентябрь 2026" },
    ],
  },
  {
    id: "6",
    name: "«АгроМаркет» сеть",
    initials: "АМ",
    color: "#10b981",
    niche: "retail",
    plan: "custom",
    fixedPrice: false,
    status: "active",
    mrr: 45000,
    healthScore: 88,
    health: { activity: 90, integrations: 85, payments: 100, support: 77 },
    connectedAt: "2024-01-20",
    hoursThisMonth: 5,
    manager: "Андрей К.",
    owner: { name: "Павел Агронов", email: "p.agronov@agromarket.ru", phone: "+7 903 789-01-23" },
    size: "45 сотрудников",
    nextAction: "Обновить договор до 70k",
    daysInStatus: 220,
    notes: "Крупнейший клиент по размеру. Кастомный тариф истекает в декабре 2026.",
    integrations: [
      { id: "1c", name: "1С", status: "ok", lastSync: "2026-09-06T07:00:00" },
      { id: "moysklad", name: "МойСклад", status: "ok", lastSync: "2026-09-06T08:00:00" },
      { id: "ozon", name: "Ozon", status: "ok", lastSync: "2026-09-06T07:30:00" },
      { id: "wb", name: "Wildberries", status: "ok", lastSync: "2026-09-06T07:45:00" },
      { id: "cdek", name: "СДЭК", status: "ok", lastSync: "2026-09-06T06:00:00" },
      { id: "whatsapp", name: "WhatsApp", status: "ok", lastSync: "2026-09-06T09:00:00" },
      { id: "telegram", name: "Telegram", status: "ok", lastSync: "2026-09-06T09:00:00" },
      { id: "site", name: "Сайт", status: "ok", lastSync: "2026-09-06T08:00:00" },
    ],
    onboardingSteps: [
      { id: "s1", title: "Анализ бизнеса", status: "done", assignee: "Андрей К.", hoursSpent: 8, dueDate: "2024-01-25" },
      { id: "s2", title: "Интеграции", status: "done", assignee: "Дмитрий Л.", hoursSpent: 22, dueDate: "2024-02-15" },
      { id: "s3", title: "Обучение команды", status: "done", assignee: "Мария С.", hoursSpent: 10, dueDate: "2024-03-01" },
      { id: "s4", title: "Запуск", status: "done", assignee: "Андрей К.", hoursSpent: 3, dueDate: "2024-03-05" },
    ],
    payments: [
      { id: "p1", date: "2026-09-01", amount: 45000, status: "paid", description: "Кастомный тариф — сентябрь 2026" },
      { id: "p2", date: "2026-08-01", amount: 45000, status: "paid", description: "Кастомный тариф — август 2026" },
    ],
  },
  {
    id: "7",
    name: "Сеть «Бытовой»",
    initials: "БТ",
    color: "#64748b",
    niche: "retail",
    plan: "full",
    fixedPrice: false,
    status: "paused",
    mrr: 0,
    healthScore: 38,
    health: { activity: 20, integrations: 50, payments: 30, support: 52 },
    connectedAt: "2023-11-05",
    hoursThisMonth: 2,
    manager: "Мария С.",
    owner: { name: "Вадим Быков", email: "v.bykov@bytovoy.ru", phone: "+7 916 890-12-34" },
    size: "30 сотрудников",
    nextAction: "Выяснить причину паузы",
    daysInStatus: 45,
    notes: "Поставил на паузу без объяснений. Задолженность 70k. Риск оттока.",
    integrations: [
      { id: "1c", name: "1С", status: "error", lastSync: "2026-07-20T12:00:00", errorMessage: "Подключение разорвано более 45 дней назад." },
      { id: "moysklad", name: "МойСклад", status: "error", lastSync: "2026-07-20T12:00:00", errorMessage: "Сессия истекла." },
      { id: "ozon", name: "Ozon", status: "ok", lastSync: "2026-09-05T10:00:00" },
      { id: "wb", name: "Wildberries", status: "ok", lastSync: "2026-09-05T11:00:00" },
      { id: "cdek", name: "СДЭК", status: "ok", lastSync: "2026-09-05T09:00:00" },
      { id: "whatsapp", name: "WhatsApp", status: "disconnected", lastSync: null },
      { id: "telegram", name: "Telegram", status: "disconnected", lastSync: null },
      { id: "site", name: "Сайт", status: "ok", lastSync: "2026-09-06T06:00:00" },
    ],
    onboardingSteps: [
      { id: "s1", title: "Анализ бизнеса", status: "done", assignee: "Мария С.", hoursSpent: 4, dueDate: "2023-11-10" },
      { id: "s2", title: "Интеграции", status: "done", assignee: "Дмитрий Л.", hoursSpent: 16, dueDate: "2023-11-25" },
      { id: "s3", title: "Обучение команды", status: "done", assignee: "Мария С.", hoursSpent: 7, dueDate: "2023-12-05" },
      { id: "s4", title: "Запуск", status: "done", assignee: "Мария С.", hoursSpent: 2, dueDate: "2023-12-10" },
    ],
    payments: [
      { id: "p1", date: "2026-08-01", amount: 70000, status: "overdue", description: "Тариф «Полный» — август 2026" },
      { id: "p2", date: "2026-07-01", amount: 70000, status: "paid", description: "Тариф «Полный» — июль 2026" },
    ],
  },
  {
    id: "8",
    name: "«ТехноПлюс»",
    initials: "ТП",
    color: "#0ea5e9",
    niche: "retail",
    plan: "full",
    fixedPrice: false,
    status: "lead",
    mrr: 0,
    healthScore: 0,
    health: { activity: 0, integrations: 0, payments: 0, support: 0 },
    connectedAt: "2026-09-01",
    hoursThisMonth: 3,
    manager: "Андрей К.",
    owner: { name: "Илья Технов", email: "i.technov@tehnoplus.ru", phone: "+7 925 901-23-45" },
    size: "22 сотрудника",
    nextAction: "Провести демо",
    daysInStatus: 5,
    notes: "Входящий лид с Ozon-форума. Интерес к полному тарифу.",
    integrations: [],
    onboardingSteps: [],
    payments: [],
  },
  {
    id: "9",
    name: "Книжный «Слово»",
    initials: "СЛ",
    color: "#f97316",
    niche: "retail",
    plan: "full",
    fixedPrice: false,
    status: "active",
    mrr: 70000,
    healthScore: 85,
    health: { activity: 88, integrations: 80, payments: 100, support: 72 },
    connectedAt: "2024-02-10",
    hoursThisMonth: 4,
    manager: "Мария С.",
    owner: { name: "Елена Книжникова", email: "e.knizh@slovo-books.ru", phone: "+7 903 012-34-56" },
    size: "10 сотрудников",
    nextAction: "Продление договора",
    daysInStatus: 195,
    notes: "Стабильный клиент. Продление в октябре 2026.",
    integrations: [
      { id: "1c", name: "1С", status: "ok", lastSync: "2026-09-06T08:00:00" },
      { id: "moysklad", name: "МойСклад", status: "ok", lastSync: "2026-09-06T09:00:00" },
      { id: "ozon", name: "Ozon", status: "ok", lastSync: "2026-09-06T08:30:00" },
      { id: "wb", name: "Wildberries", status: "ok", lastSync: "2026-09-06T08:45:00" },
      { id: "cdek", name: "СДЭК", status: "ok", lastSync: "2026-09-06T07:00:00" },
      { id: "whatsapp", name: "WhatsApp", status: "ok", lastSync: "2026-09-06T09:00:00" },
      { id: "telegram", name: "Telegram", status: "ok", lastSync: "2026-09-06T09:00:00" },
      { id: "site", name: "Сайт", status: "ok", lastSync: "2026-09-06T08:00:00" },
    ],
    onboardingSteps: [
      { id: "s1", title: "Анализ бизнеса", status: "done", assignee: "Мария С.", hoursSpent: 3, dueDate: "2024-02-15" },
      { id: "s2", title: "Интеграции", status: "done", assignee: "Дмитрий Л.", hoursSpent: 9, dueDate: "2024-02-28" },
      { id: "s3", title: "Обучение команды", status: "done", assignee: "Мария С.", hoursSpent: 5, dueDate: "2024-03-08" },
      { id: "s4", title: "Запуск", status: "done", assignee: "Мария С.", hoursSpent: 2, dueDate: "2024-03-12" },
    ],
    payments: [
      { id: "p1", date: "2026-09-01", amount: 70000, status: "paid", description: "Тариф «Полный» — сентябрь 2026" },
      { id: "p2", date: "2026-08-01", amount: 70000, status: "paid", description: "Тариф «Полный» — август 2026" },
    ],
  },
  {
    id: "10",
    name: "«СтройМастер»",
    initials: "СМ",
    color: "#84cc16",
    niche: "services",
    plan: "custom",
    fixedPrice: false,
    status: "active",
    mrr: 60000,
    healthScore: 91,
    health: { activity: 94, integrations: 88, payments: 100, support: 82 },
    connectedAt: "2023-12-01",
    hoursThisMonth: 3,
    manager: "Дмитрий Л.",
    owner: { name: "Роман Строев", email: "r.stroev@stroymaster.ru", phone: "+7 916 123-45-67" },
    size: "35 сотрудников",
    nextAction: "Ежеквартальный отзыв",
    daysInStatus: 240,
    notes: "Лучший клиент по ROI. Всё работает отлично.",
    integrations: [
      { id: "1c", name: "1С", status: "ok", lastSync: "2026-09-06T07:30:00" },
      { id: "moysklad", name: "МойСклад", status: "ok", lastSync: "2026-09-06T08:00:00" },
      { id: "ozon", name: "Ozon", status: "disconnected", lastSync: null },
      { id: "wb", name: "Wildberries", status: "disconnected", lastSync: null },
      { id: "cdek", name: "СДЭК", status: "ok", lastSync: "2026-09-06T07:00:00" },
      { id: "whatsapp", name: "WhatsApp", status: "ok", lastSync: "2026-09-06T09:00:00" },
      { id: "telegram", name: "Telegram", status: "ok", lastSync: "2026-09-06T09:00:00" },
      { id: "site", name: "Сайт", status: "ok", lastSync: "2026-09-06T08:00:00" },
    ],
    onboardingSteps: [
      { id: "s1", title: "Анализ бизнеса", status: "done", assignee: "Дмитрий Л.", hoursSpent: 5, dueDate: "2023-12-07" },
      { id: "s2", title: "Интеграции", status: "done", assignee: "Дмитрий Л.", hoursSpent: 14, dueDate: "2023-12-22" },
      { id: "s3", title: "Обучение команды", status: "done", assignee: "Мария С.", hoursSpent: 6, dueDate: "2024-01-05" },
      { id: "s4", title: "Запуск", status: "done", assignee: "Дмитрий Л.", hoursSpent: 2, dueDate: "2024-01-10" },
    ],
    payments: [
      { id: "p1", date: "2026-09-01", amount: 60000, status: "paid", description: "Кастомный тариф — сентябрь 2026" },
      { id: "p2", date: "2026-08-01", amount: 60000, status: "paid", description: "Кастомный тариф — август 2026" },
    ],
  },
  {
    id: "11",
    name: "SportLife",
    initials: "СЛ",
    color: "#14b8a6",
    niche: "retail",
    plan: "early_access",
    fixedPrice: true,
    status: "onboarding",
    mrr: 5000,
    healthScore: 58,
    health: { activity: 60, integrations: 40, payments: 100, support: 32 },
    connectedAt: "2026-07-20",
    hoursThisMonth: 28,
    manager: "Дмитрий Л.",
    owner: { name: "Кирилл Спортов", email: "k.sportov@sportlife.ru", phone: "+7 967 234-56-78" },
    size: "14 сотрудников",
    nextAction: "Завершить интеграцию WB",
    daysInStatus: 48,
    notes: "Онбординг затягивается. Команда клиента медленно реагирует.",
    integrations: [
      { id: "1c", name: "1С", status: "ok", lastSync: "2026-09-05T16:00:00" },
      { id: "moysklad", name: "МойСклад", status: "ok", lastSync: "2026-09-05T17:00:00" },
      { id: "ozon", name: "Ozon", status: "ok", lastSync: "2026-09-05T18:00:00" },
      { id: "wb", name: "Wildberries", status: "error", lastSync: "2026-09-03T10:00:00", errorMessage: "Магазин не подтверждён на стороне WB." },
      { id: "cdek", name: "СДЭК", status: "disconnected", lastSync: null },
      { id: "whatsapp", name: "WhatsApp", status: "ok", lastSync: "2026-09-06T09:00:00" },
      { id: "telegram", name: "Telegram", status: "disconnected", lastSync: null },
      { id: "site", name: "Сайт", status: "disconnected", lastSync: null },
    ],
    onboardingSteps: [
      { id: "s1", title: "Анализ бизнеса", status: "done", assignee: "Дмитрий Л.", hoursSpent: 4, dueDate: "2026-07-27" },
      { id: "s2", title: "Интеграции", status: "in_progress", assignee: "Дмитрий Л.", hoursSpent: 20, dueDate: "2026-09-10" },
      { id: "s3", title: "Обучение команды", status: "pending", assignee: "Мария С.", hoursSpent: 0, dueDate: "2026-09-25" },
      { id: "s4", title: "Запуск", status: "pending", assignee: "Дмитрий Л.", hoursSpent: 0, dueDate: "2026-10-05" },
    ],
    payments: [
      { id: "p1", date: "2026-07-20", amount: 5000, status: "paid", description: "Ранний доступ — июль 2026" },
      { id: "p2", date: "2026-08-01", amount: 5000, status: "paid", description: "Ранний доступ — август 2026" },
      { id: "p3", date: "2026-09-01", amount: 5000, status: "paid", description: "Ранний доступ — сентябрь 2026" },
    ],
  },
  {
    id: "12",
    name: "Цветочный «Флора»",
    initials: "ФЛ",
    color: "#d946ef",
    niche: "retail",
    plan: "full",
    fixedPrice: false,
    status: "churned",
    mrr: 0,
    healthScore: 0,
    health: { activity: 0, integrations: 0, payments: 0, support: 0 },
    connectedAt: "2024-06-01",
    hoursThisMonth: 0,
    manager: "Мария С.",
    owner: { name: "Наталья Флорова", email: "n.florova@flora.ru", phone: "+7 916 345-67-89" },
    size: "5 сотрудников",
    nextAction: "—",
    daysInStatus: 30,
    notes: "Отказались из-за бюджета. Возможно вернутся на более низком тарифе.",
    integrations: [],
    onboardingSteps: [],
    payments: [
      { id: "p1", date: "2026-07-01", amount: 70000, status: "paid", description: "Тариф «Полный» — июль 2026" },
      { id: "p2", date: "2026-06-01", amount: 70000, status: "paid", description: "Тариф «Полный» — июнь 2026" },
    ],
  },
];

/**
 * Стадия воронки для клиентов, которые уже прошли демо или договор.
 * Раньше эта карта жила прямо в компоненте доски onboarding-пайплайна.
 */
const STAGE_SEED: Record<string, ClientStage> = {
  "1": "active",
  "2": "active",
  "4": "active",
  "6": "active",
  "8": "lead",
  "9": "active",
  "10": "active",
};

export const mockClients: Client[] = seed.map((client) => ({
  ...client,
  stage: STAGE_SEED[client.id] ?? client.status,
}));
